import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "hi" | "mr" | "te";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "Welcome to Eylin",
    "app.subtitle": "Your friendly AI Loan Assistant for instant loan approvals. Choose your track to get started.",
    "badge.voice": "Voice Enabled",
    "badge.languages": "4 Languages",
    "badge.security": "Advanced Security & Blockchain",
    "track1.title": "Track 1 - Metro Profit Loans",
    "track1.desc": "Premium loan products for salaried professionals and established businesses with competitive rates and quick processing.",
    "track1.benefit1": "Higher loan amounts up to ₹50 Lakhs",
    "track1.benefit2": "Competitive interest rates starting from 9.5%",
    "track1.benefit3": "Instant digital approvals for eligible customers",
    "track2.title": "Track 2 - Tier 2 Micro-Loans",
    "track2.desc": "Accessible micro-financing solutions for small businesses and individuals in tier-2 cities with flexible terms.",
    "track2.benefit1": "Loans from ₹50,000 to ₹10 Lakhs",
    "track2.benefit2": "Simplified documentation process",
    "track2.benefit3": "Support for self-employed and new businesses",
    "button.explore": "Explore",
    "button.home": "Home",
    "button.return": "Return to Main Menu",
    "button.apply": "Apply Now",
    "button.send": "Send",
    "button.submit": "Submit Documents",
    "button.download": "Download Sanction Letter",
    "button.demo": "Demo Approval",
    "loan.car": "Car Loan",
    "loan.education": "Education Loan",
    "loan.business": "Business Loan",
    "loan.twowheeler": "Two-Wheeler Loan",
    "loan.home": "Home Improvement Loan",
    "loan.personal": "Personal Loan",
    "loan.other": "Other Loan Types",
    "loan.car.title": "Vehicle Finance",
    "loan.car.desc": "Get your dream car with flexible repayment options and competitive interest rates.",
    "loan.education.title": "Education Finance",
    "loan.education.desc": "Invest in your future with our education loans for courses and institutions worldwide.",
    "loan.business.title": "Business Expansion",
    "loan.business.desc": "Grow your business with quick approvals and minimal documentation requirements.",
    "loan.twowheeler.title": "Two-Wheeler Finance",
    "loan.twowheeler.desc": "Affordable financing for bikes and scooters with easy EMI options.",
    "loan.home.title": "Home Renovation",
    "loan.home.desc": "Quick loans for home repairs, renovations, and improvements.",
    "loan.personal.title": "Personal Finance",
    "loan.personal.desc": "Flexible personal loans for medical, wedding, or emergency needs.",
    "loan.other.title": "Other Loan Types",
    "loan.other.desc": "Explore additional loan products tailored to your specific needs and requirements.",
    "loan.skillcourse": "Skill-Course Micro-Loan",
    "loan.skillcourse.title": "Skill-Course Micro-Loan",
    "loan.skillcourse.desc": "Small loans to join skill development courses and upskill yourself for better opportunities.",
    "loan.rentdeposit": "Rent-Deposit Support Loan",
    "loan.rentdeposit.title": "Rent-Deposit Support Loan",
    "loan.rentdeposit.desc": "Get help with your rent deposit when moving to a new city for work.",
    "loan.digitalcredit": "Digital-Credit Builder Loan",
    "loan.digitalcredit.title": "Digital-Credit Builder Loan",
    "loan.digitalcredit.desc": "Build your first credit score using your digital activity like bill payments and UPI usage.",
    "loan.smallbusiness": "Small-Business Starter Loan",
    "loan.smallbusiness.title": "Small-Business Starter Loan",
    "loan.smallbusiness.desc": "Micro-loans for small businesses and entrepreneurs to grow their ventures.",
    "chat.placeholder": "Type your message...",
    "chat.with": "Chat with Eylin",
    "upload.label": "Upload Documents",
    "upload.drop": "Drop files here or click to upload",
    "upload.supported": "Supported:",
    "approval.badge": "Approved",
    "approval.congrats": "Congratulations",
    "approval.message": "Your {loanType} has been approved",
    "approval.amount": "Loan Amount",
    "approval.rate": "Interest Rate",
    "approval.tenure": "Tenure",
    "approval.letter": "Sanction Letter",
    "approval.doc": "Official approval document",
    "track.select": "Select a loan type to start your application",
    "personality": "Eylin's personality: empathetic • accurate • helpful",
    "amount": "Amount",
    "interestrate": "Interest Rate",
    "tenure": "Tenure",
    "upto": "Up to",
    "varies": "Varies",
    "competitive": "Competitive rates",
    "flexible": "Flexible terms",
  },
  hi: {
    "app.title": "एलिन में आपका स्वागत है",
    "app.subtitle": "तत्काल लोन स्वीकृति के लिए आपका मित्रवत AI लोन सहायक। शुरू करने के लिए अपना ट्रैक चुनें।",
    "badge.voice": "वॉइस सक्षम",
    "badge.languages": "4 भाषाएँ",
    "badge.security": "उन्नत सुरक्षा और ब्लॉकचेन",
    "track1.title": "ट्रैक 1 - मेट्रो प्रॉफिट लोन",
    "track1.desc": "वेतनभोगी पेशेवरों और स्थापित व्यवसायों के लिए प्रतिस्पर्धी दरों और त्वरित प्रसंस्करण के साथ प्रीमियम लोन उत्पाद।",
    "track1.benefit1": "₹50 लाख तक उच्च लोन राशि",
    "track1.benefit2": "9.5% से शुरू होने वाली प्रतिस्पर्धी ब्याज दरें",
    "track1.benefit3": "पात्र ग्राहकों के लिए तत्काल डिजिटल स्वीकृति",
    "track2.title": "ट्रैक 2 - टियर 2 माइक्रो-लोन",
    "track2.desc": "लचीली शर्तों के साथ टियर-2 शहरों में छोटे व्यवसायों और व्यक्तियों के लिए सुलभ सूक्ष्म-वित्तपोषण समाधान।",
    "track2.benefit1": "₹50,000 से ₹10 लाख तक लोन",
    "track2.benefit2": "सरलीकृत दस्तावेज़ीकरण प्रक्रिया",
    "track2.benefit3": "स्व-नियोजित और नए व्यवसायों के लिए समर्थन",
    "button.explore": "अन्वेषण करें",
    "button.home": "होम",
    "button.return": "मुख्य मेनू पर लौटें",
    "button.apply": "अभी आवेदन करें",
    "button.send": "भेजें",
    "button.submit": "दस्तावेज़ जमा करें",
    "button.download": "स्वीकृति पत्र डाउनलोड करें",
    "button.demo": "डेमो स्वीकृति",
    "loan.car": "कार लोन",
    "loan.education": "शिक्षा लोन",
    "loan.business": "बिजनेस लोन",
    "loan.twowheeler": "टू-व्हीलर लोन",
    "loan.home": "होम इम्प्रूवमेंट लोन",
    "loan.personal": "व्यक्तिगत लोन",
    "loan.other": "अन्य लोन प्रकार",
    "loan.car.title": "वाहन वित्त",
    "loan.car.desc": "लचीले पुनर्भुगतान विकल्पों और प्रतिस्पर्धी ब्याज दरों के साथ अपनी सपनों की कार पाएं।",
    "loan.education.title": "शिक्षा वित्त",
    "loan.education.desc": "दुनिया भर के पाठ्यक्रमों और संस्थानों के लिए हमारे शिक्षा लोन के साथ अपने भविष्य में निवेश करें।",
    "loan.business.title": "व्यवसाय विस्तार",
    "loan.business.desc": "त्वरित स्वीकृति और न्यूनतम दस्तावेज़ीकरण आवश्यकताओं के साथ अपने व्यवसाय को बढ़ाएं।",
    "loan.twowheeler.title": "टू-व्हीलर वित्त",
    "loan.twowheeler.desc": "आसान EMI विकल्पों के साथ बाइक और स्कूटर के लिए किफायती वित्तपोषण।",
    "loan.home.title": "होम रेनोवेशन",
    "loan.home.desc": "घर की मरम्मत, नवीनीकरण और सुधार के लिए त्वरित लोन।",
    "loan.personal.title": "व्यक्तिगत वित्त",
    "loan.personal.desc": "चिकित्सा, शादी या आपातकालीन जरूरतों के लिए लचीले व्यक्तिगत लोन।",
    "loan.other.title": "अन्य लोन प्रकार",
    "loan.other.desc": "आपकी विशिष्ट आवश्यकताओं के अनुरूप अतिरिक्त लोन उत्पादों का अन्वेषण करें।",
    "loan.skillcourse": "स्किल-कोर्स माइक्रो-लोन",
    "loan.skillcourse.title": "स्किल-कोर्स माइक्रो-लोन",
    "loan.skillcourse.desc": "कौशल विकास पाठ्यक्रमों में शामिल होने और बेहतर अवसरों के लिए खुद को अपस्किल करने के लिए छोटे लोन।",
    "loan.rentdeposit": "किराया-जमा सहायता लोन",
    "loan.rentdeposit.title": "किराया-जमा सहायता लोन",
    "loan.rentdeposit.desc": "काम के लिए नए शहर में जाने पर अपने किराया जमा के साथ मदद प्राप्त करें।",
    "loan.digitalcredit": "डिजिटल-क्रेडिट बिल्डर लोन",
    "loan.digitalcredit.title": "डिजिटल-क्रेडिट बिल्डर लोन",
    "loan.digitalcredit.desc": "बिल भुगतान और UPI उपयोग जैसी अपनी डिजिटल गतिविधि का उपयोग करके अपना पहला क्रेडिट स्कोर बनाएं।",
    "loan.smallbusiness": "छोटा-व्यवसाय स्टार्टर लोन",
    "loan.smallbusiness.title": "छोटा-व्यवसाय स्टार्टर लोन",
    "loan.smallbusiness.desc": "छोटे व्यवसायों और उद्यमियों के लिए अपने उद्यमों को बढ़ाने के लिए माइक्रो-लोन।",
    "chat.placeholder": "अपना संदेश टाइप करें...",
    "chat.with": "एलिन के साथ चैट करें",
    "upload.label": "दस्तावेज़ अपलोड करें",
    "upload.drop": "फ़ाइलें यहां छोड़ें या अपलोड करने के लिए क्लिक करें",
    "upload.supported": "समर्थित:",
    "approval.badge": "स्वीकृत",
    "approval.congrats": "बधाई हो",
    "approval.message": "आपका {loanType} स्वीकृत हो गया है",
    "approval.amount": "लोन राशि",
    "approval.rate": "ब्याज दर",
    "approval.tenure": "अवधि",
    "approval.letter": "स्वीकृति पत्र",
    "approval.doc": "आधिकारिक स्वीकृति दस्तावेज़",
    "track.select": "अपना आवेदन शुरू करने के लिए एक लोन प्रकार चुनें",
    "personality": "एलिन का व्यक्तित्व: सहानुभूतिपूर्ण • सटीक • सहायक",
    "amount": "राशि",
    "interestrate": "ब्याज दर",
    "tenure": "अवधि",
    "upto": "तक",
    "varies": "भिन्न होता है",
    "competitive": "प्रतिस्पर्धी दरें",
    "flexible": "लचीली शर्तें",
  },
  mr: {
    "app.title": "एलिनमध्ये आपले स्वागत आहे",
    "app.subtitle": "त्वरित कर्ज मंजुरीसाठी तुमचा मैत्रीपूर्ण AI कर्ज सहाय्यक. सुरुवात करण्यासाठी तुमचा ट्रॅक निवडा.",
    "badge.voice": "व्हॉइस सक्षम",
    "badge.languages": "4 भाषा",
    "badge.security": "प्रगत सुरक्षा आणि ब्लॉकचेन",
    "track1.title": "ट्रॅक 1 - मेट्रो प्रॉफिट कर्ज",
    "track1.desc": "पगारदार व्यावसायिक आणि स्थापित व्यवसायांसाठी स्पर्धात्मक दर आणि जलद प्रक्रियेसह प्रीमियम कर्ज उत्पादने.",
    "track1.benefit1": "₹50 लाख पर्यंत उच्च कर्ज रक्कम",
    "track1.benefit2": "9.5% पासून सुरू होणारे स्पर्धात्मक व्याज दर",
    "track1.benefit3": "पात्र ग्राहकांसाठी त्वरित डिजिटल मंजुरी",
    "track2.title": "ट्रॅक 2 - टियर 2 मायक्रो-कर्ज",
    "track2.desc": "लवचिक अटींसह टियर-2 शहरांमधील लहान व्यवसाय आणि व्यक्तींसाठी सुलभ सूक्ष्म-वित्तपोषण उपाय.",
    "track2.benefit1": "₹50,000 ते ₹10 लाख पर्यंत कर्ज",
    "track2.benefit2": "सरलीकृत कागदपत्र प्रक्रिया",
    "track2.benefit3": "स्वयंरोजगार आणि नवीन व्यवसायांसाठी समर्थन",
    "button.explore": "एक्सप्लोर करा",
    "button.home": "होम",
    "button.return": "मुख्य मेनूवर परत या",
    "button.apply": "आता अर्ज करा",
    "button.send": "पाठवा",
    "button.submit": "कागदपत्रे सबमिट करा",
    "button.download": "मंजूरी पत्र डाउनलोड करा",
    "button.demo": "डेमो मंजूरी",
    "loan.car": "कार कर्ज",
    "loan.education": "शिक्षण कर्ज",
    "loan.business": "व्यवसाय कर्ज",
    "loan.twowheeler": "टू-व्हीलर कर्ज",
    "loan.home": "होम इम्प्रूव्हमेंट कर्ज",
    "loan.personal": "वैयक्तिक कर्ज",
    "loan.other": "इतर कर्ज प्रकार",
    "loan.car.title": "वाहन वित्त",
    "loan.car.desc": "लवचिक परतफेड पर्याय आणि स्पर्धात्मक व्याज दरांसह तुमची स्वप्नातील कार मिळवा.",
    "loan.education.title": "शिक्षण वित्त",
    "loan.education.desc": "जगभरातील अभ्यासक्रम आणि संस्थांसाठी आमच्या शिक्षण कर्जासह तुमच्या भविष्यात गुंतवणूक करा.",
    "loan.business.title": "व्यवसाय विस्तार",
    "loan.business.desc": "जलद मंजुरी आणि किमान कागदपत्र आवश्यकतांसह तुमचा व्यवसाय वाढवा.",
    "loan.twowheeler.title": "टू-व्हीलर वित्त",
    "loan.twowheeler.desc": "सोप्या EMI पर्यायांसह बाइक आणि स्कूटरसाठी परवडणारे वित्तपोषण.",
    "loan.home.title": "होम रेनोवेशन",
    "loan.home.desc": "घर दुरुस्ती, नूतनीकरण आणि सुधारणांसाठी जलद कर्ज.",
    "loan.personal.title": "वैयक्तिक वित्त",
    "loan.personal.desc": "वैद्यकीय, लग्न किंवा आपत्कालीन गरजांसाठी लवचिक वैयक्तिक कर्ज.",
    "loan.other.title": "इतर कर्ज प्रकार",
    "loan.other.desc": "तुमच्या विशिष्ट गरजा आणि आवश्यकतांनुसार अतिरिक्त कर्ज उत्पादने एक्सप्लोर करा.",
    "loan.skillcourse": "स्किल-कोर्स मायक्रो-कर्ज",
    "loan.skillcourse.title": "स्किल-कोर्स मायक्रो-कर्ज",
    "loan.skillcourse.desc": "कौशल्य विकास अभ्यासक्रमांमध्ये सामील होण्यासाठी आणि चांगल्या संधींसाठी स्वतःला अपस्किल करण्यासाठी लहान कर्जे.",
    "loan.rentdeposit": "भाडे-जमा समर्थन कर्ज",
    "loan.rentdeposit.title": "भाडे-जमा समर्थन कर्ज",
    "loan.rentdeposit.desc": "कामासाठी नवीन शहरात जाताना तुमच्या भाड्याच्या जमेसाठी मदत मिळवा.",
    "loan.digitalcredit": "डिजिटल-क्रेडिट बिल्डर कर्ज",
    "loan.digitalcredit.title": "डिजिटल-क्रेडिट बिल्डर कर्ज",
    "loan.digitalcredit.desc": "बिल पेमेंट आणि UPI वापरासारख्या तुमच्या डिजिटल क्रियाकलापाचा वापर करून तुमचा पहिला क्रेडिट स्कोअर तयार करा.",
    "loan.smallbusiness": "लहान-व्यवसाय स्टार्टर कर्ज",
    "loan.smallbusiness.title": "लहान-व्यवसाय स्टार्टर कर्ज",
    "loan.smallbusiness.desc": "लहान व्यवसाय आणि उद्योजकांसाठी त्यांच्या उद्योगांना वाढवण्यासाठी मायक्रो-कर्जे.",
    "chat.placeholder": "तुमचा संदेश टाइप करा...",
    "chat.with": "एलिनशी चॅट करा",
    "upload.label": "कागदपत्रे अपलोड करा",
    "upload.drop": "फायली येथे टाका किंवा अपलोड करण्यासाठी क्लिक करा",
    "upload.supported": "समर्थित:",
    "approval.badge": "मंजूर",
    "approval.congrats": "अभिनंदन",
    "approval.message": "तुमचे {loanType} मंजूर झाले आहे",
    "approval.amount": "कर्ज रक्कम",
    "approval.rate": "व्याज दर",
    "approval.tenure": "कालावधी",
    "approval.letter": "मंजूरी पत्र",
    "approval.doc": "अधिकृत मंजूरी दस्तऐवज",
    "track.select": "तुमचा अर्ज सुरू करण्यासाठी कर्ज प्रकार निवडा",
    "personality": "एलिनचे व्यक्तिमत्त्व: सहानुभूतीपूर्ण • अचूक • उपयुक्त",
    "amount": "रक्कम",
    "interestrate": "व्याज दर",
    "tenure": "कालावधी",
    "upto": "पर्यंत",
    "varies": "बदलते",
    "competitive": "स्पर्धात्मक दर",
    "flexible": "लवचिक अटी",
  },
  te: {
    "app.title": "ఐలిన్‌కు స్వాగతం",
    "app.subtitle": "తక్షణ రుణ ఆమోదాల కోసం మీ స్నేహపూర్వక AI రుణ సహాయకుడు. ప్రారంభించడానికి మీ ట్రాక్‌ను ఎంచుకోండి.",
    "badge.voice": "వాయిస్ ఎనేబుల్ చేయబడింది",
    "badge.languages": "4 భాషలు",
    "badge.security": "అధునాతన భద్రత & బ్లాక్‌చెయిన్",
    "track1.title": "ట్రాక్ 1 - మెట్రో ప్రాఫిట్ లోన్స్",
    "track1.desc": "పోటీ రేట్లు మరియు వేగవంతమైన ప్రాసెసింగ్‌తో జీతం పొందే నిపుణులు మరియు స్థాపించబడిన వ్యాపారాల కోసం ప్రీమియం రుణ ఉత్పత్తులు.",
    "track1.benefit1": "₹50 లక్షల వరకు అధిక రుణ మొత్తాలు",
    "track1.benefit2": "9.5% నుండి ప్రారంభమయ్యే పోటీ వడ్డీ రేట్లు",
    "track1.benefit3": "అర్హులైన కస్టమర్‌ల కోసం తక్షణ డిజిటల్ ఆమోదాలు",
    "track2.title": "ట్రాక్ 2 - టైర్ 2 మైక్రో-లోన్స్",
    "track2.desc": "సౌకర్యవంతమైన నిబంధనలతో టైర్-2 నగరాల్లోని చిన్న వ్యాపారాలు మరియు వ్యక్తుల కోసం అందుబాటులో ఉన్న సూక్ష్మ-ఫైనాన్సింగ్ పరిష్కారాలు.",
    "track2.benefit1": "₹50,000 నుండి ₹10 లక్షల వరకు రుణాలు",
    "track2.benefit2": "సరళీకృత డాక్యుమెంటేషన్ ప్రక్రియ",
    "track2.benefit3": "స్వయం ఉపాధి మరియు కొత్త వ్యాపారాలకు మద్దతు",
    "button.explore": "అన్వేషించండి",
    "button.home": "హోమ్",
    "button.return": "ప్రధాన మెనుకు తిరిగి వెళ్లండి",
    "button.apply": "ఇప్పుడే దరఖాస్తు చేయండి",
    "button.send": "పంపండి",
    "button.submit": "పత్రాలను సమర్పించండి",
    "button.download": "మంజూరు లేఖను డౌన్‌లోడ్ చేయండి",
    "button.demo": "డెమో ఆమోదం",
    "loan.car": "కార్ లోన్",
    "loan.education": "విద్యా రుణం",
    "loan.business": "వ్యాపార రుణం",
    "loan.twowheeler": "టూ-వీలర్ లోన్",
    "loan.home": "గృహ మెరుగుదల రుణం",
    "loan.personal": "వ్యక్తిగత రుణం",
    "loan.other": "ఇతర రుణ రకాలు",
    "loan.car.title": "వాహన ఫైనాన్స్",
    "loan.car.desc": "సౌకర్యవంతమైన తిరిగి చెల్లింపు ఎంపికలు మరియు పోటీ వడ్డీ రేట్లతో మీ కలల కారును పొందండి.",
    "loan.education.title": "విద్యా ఫైనాన్స్",
    "loan.education.desc": "ప్రపంచవ్యాప్తంగా ఉన్న కోర్సులు మరియు సంస్థల కోసం మా విద్యా రుణాలతో మీ భవిష్యత్తులో పెట్టుబడి పెట్టండి.",
    "loan.business.title": "వ్యాపార విస్తరణ",
    "loan.business.desc": "వేగవంతమైన ఆమోదాలు మరియు కనిష్ట డాక్యుమెంటేషన్ అవసరాలతో మీ వ్యాపారాన్ని పెంచుకోండి.",
    "loan.twowheeler.title": "టూ-వీలర్ ఫైనాన్స్",
    "loan.twowheeler.desc": "సులభ EMI ఎంపికలతో బైక్‌లు మరియు స్కూటర్‌ల కోసం సరసమైన ఫైనాన్సింగ్.",
    "loan.home.title": "గృహ పునర్నిర్మాణం",
    "loan.home.desc": "గృహ మరమ్మతులు, పునర్నిర్మాణాలు మరియు మెరుగుదలల కోసం శీఘ్ర రుణాలు.",
    "loan.personal.title": "వ్యక్తిగత ఫైనాన్స్",
    "loan.personal.desc": "వైద్య, వివాహ లేదా అత్యవసర అవసరాల కోసం సౌకర్యవంతమైన వ్యక్తిగత రుణాలు.",
    "loan.other.title": "ఇతర రుణ రకాలు",
    "loan.other.desc": "మీ నిర్దిష్ట అవసరాలు మరియు అవసరాలకు అనుగుణంగా అదనపు రుణ ఉత్పత్తులను అన్వేషించండి.",
    "loan.skillcourse": "స్కిల్-కోర్స్ మైక్రో-లోన్",
    "loan.skillcourse.title": "స్కిల్-కోర్స్ మైక్రో-లోన్",
    "loan.skillcourse.desc": "నైపుణ్య అభివృద్ధి కోర్సులలో చేరడానికి మరియు మంచి అవకాశాల కోసం మిమ్మల్ని మీరు అప్‌స్కిల్ చేసుకోవడానికి చిన్న రుణాలు.",
    "loan.rentdeposit": "అద్దె-డిపాజిట్ మద్దతు రుణం",
    "loan.rentdeposit.title": "అద్దె-డిపాజిట్ మద్దతు రుణం",
    "loan.rentdeposit.desc": "పని కోసం కొత్త నగరానికి వెళ్లేటప్పుడు మీ అద్దె డిపాజిట్‌కు సహాయం పొందండి.",
    "loan.digitalcredit": "డిజిటల్-క్రెడిట్ బిల్డర్ లోన్",
    "loan.digitalcredit.title": "డిజిటల్-క్రెడిట్ బిల్డర్ లోన్",
    "loan.digitalcredit.desc": "బిల్ చెల్లింపులు మరియు UPI వినియోగం వంటి మీ డిజిటల్ కార్యకలాపాలను ఉపయోగించి మీ మొదటి క్రెడిట్ స్కోర్‌ను నిర్మించండి.",
    "loan.smallbusiness": "చిన్న-వ్యాపార స్టార్టర్ లోన్",
    "loan.smallbusiness.title": "చిన్న-వ్యాపార స్టార్టర్ లోన్",
    "loan.smallbusiness.desc": "చిన్న వ్యాపారాలు మరియు వ్యవస్థాపకుల కోసం వారి వ్యాపారాలను పెంచడానికి మైక్రో-లోన్స్.",
    "chat.placeholder": "మీ సందేశాన్ని టైప్ చేయండి...",
    "chat.with": "ఐలిన్‌తో చాట్ చేయండి",
    "upload.label": "పత్రాలను అప్‌లోడ్ చేయండి",
    "upload.drop": "ఫైల్‌లను ఇక్కడ వదలండి లేదా అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    "upload.supported": "మద్దతు ఉంది:",
    "approval.badge": "ఆమోదించబడింది",
    "approval.congrats": "అభినందనలు",
    "approval.message": "మీ {loanType} ఆమోదించబడింది",
    "approval.amount": "రుణ మొత్తం",
    "approval.rate": "వడ్డీ రేటు",
    "approval.tenure": "కాలవ్యవధి",
    "approval.letter": "మంజూరు లేఖ",
    "approval.doc": "అధికారిక ఆమోద పత్రం",
    "track.select": "మీ దరఖాస్తును ప్రారంభించడానికి రుణ రకాన్ని ఎంచుకోండి",
    "personality": "ఐలిన్ వ్యక్తిత్వం: సానుభూతిగల • ఖచ్చితమైన • సహాయకరమైన",
    "amount": "మొత్తం",
    "interestrate": "వడ్డీ రేటు",
    "tenure": "కాలవ్యవధి",
    "upto": "వరకు",
    "varies": "మారుతుంది",
    "competitive": "పోటీ రేట్లు",
    "flexible": "సౌకర్యవంతమైన నిబంధనలు",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
